### ISSUE TITLE
Clarify security considerations

### ISSUE THREAD

**Issue by dbohdan** [danburzo/hred#4]
Why should one be mindful when feeding untrusted HTML into hred if it doesn't run scripts?

**Comment by danburzo** [comment]
Good question! I meant that as both reassurance and warning. 

Warning in the sense that `hred` uses `jsdom`, which is more than a passive DOM parser — one of its distinguishing features is the ability to run scripts. I guess the mere presence of this ability makes a vulnerability in `jsdom` _theoretically possible_, if highly unlikely (and, at the time of writing, unprecedented AFAICT). Reassurance in the sense that `jsdom` is configured to prevent unverified markup from doing any damage outside such a vulnerability.

I do agree that the way it is phrased may be both disconcerting and non-actionable.

**Comment by dbohdan** [comment]
Thanks for the explanation.  You should put something like it in the readme.

**Comment by danburzo** [comment]
I've changed the wording in https://github.com/danburzo/hred/issues/5, please let me know what you think!

**Comment by danburzo** [comment]
Addressed in https://github.com/danburzo/hred/commit/bcc5dc628b37e9626f9a0a055878d58053daf3e4, hopefully in a satisfactory fashion. Thanks again for bringing this up, @dbohdan!

**Comment by dbohdan** [comment]
It's definitely better.  Thanks for the link!
