### ISSUE TITLE
Flag to read query from file.

### ISSUE THREAD

**Issue by tejing1** [danburzo/hred#6]
I've found myself writing `hred "$(<filename)"` somewhat frequently, as queries are often just a little too large to ergonomically inline in a script.

Most major text stream processing tools with their own domain specific language, like `jq`, `sed`, and `awk`, can be invoked as `prog -f filename` instead of `prog 'dsl code'`, so it would make sense for `hred` to have the same functionality.

**Comment by danburzo** [comment]
I think that's a great idea, @tejing1. `-f` seems to be a common choice for the short option, and I'm thinking either `--from` or `--file` as the long counterpart.

**Comment by tejing1** [comment]
`awk --file`
`sed --file`
`jq --from-file`

`--file` is probably the least surprising long option name.

Not sure what other tools to compare against off the top of my head.

**Comment by danburzo** [comment]
Yeah, ripgrep uses `--file` as well. I didn't like it at first because I felt `--from` is a bit more explicit, but I will change it for consistency.

**Comment by danburzo** [comment]
The `-f` / `--file` option is available in `hred@1.5.0`. Thanks for the suggestion!

**Comment by tejing1** [comment]
You're welcome, and thanks for the super quick response. Not to mention for making my personal favorite tool in this category. :smile:
